services:
  insomnia-wallet-web:
    build:
      context: ../../
      dockerfile: apps/web/Dockerfile
    container_name: insomnia-wallet-web
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - insomnia-wallet-network

networks:
  insomnia-wallet-network:
    name: insomnia-wallet-network
    external: true