services:
  api:
    build:
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - DEBUG=true
    command: pnpm dev
    volumes:
      - ./apps/api:/app
      - /app/node_modules
      - /app/dist